apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: hexagonal-ddd-api
    newName: your-registry/hexagonal-ddd-api
    newTag: latest
